[tool.poetry]
name = "jobcontrol"
version = "0.1.0"
description = ""
authors = ["morevi <morevi@correo.ugr.es>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
invoke = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
