name: build-publish

on:
  push:
    branches:
      - main
    paths:
      # only if these files had changes
      - Dockerfile
      - pyproject.toml

  build:
    runs-on: ubuntu-latest
    steps:
      # get project code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: morevi/jobcontrol
