name: "DockerHub"

on:
  push:
    branches:
      - main
      - objetivo-5
    paths:
      # only if these files had changes
      - Dockerfile
      - pyproject.toml
      - .github/workflows/dockerhub.yml

jobs:
  buildnpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: morevi/jobcontrol:latest

